# Generated by Django 3.2.7 on 2021-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción'),
        ),
    ]
